### ISSUE TITLE
It's just thank you

### ISSUE THREAD

**Issue by CRAG666** [max-0406/autoclose.nvim#1]
I just wanted to thank you for writing such a wonderful plugin that really works, in fact this is so cool that it doesn't interfere with autocomplete and needless to say this was one of the reasons I ditched nvim-autopairs. Thanks a lot.

**Comment by CRAG666** [comment]
perhaps a feature suggestion is the ability to wrap. But it's just a suggestion

**Comment by max-0406** [comment]
Thanks for your support and suggestion. I will try to improve this plugin and add the ability to wrap.
